# Generated by Django 5.2.5 on 2025-11-11 13:32

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='amenities',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('parking', 'Parking'), ('lift', 'Lift'), ('security', 'Security'), ('furnished', 'Furnished'), ('balcony', 'Balcony'), ('powerbackup', 'Power Backup')], max_length=200),
        ),
        migrations.DeleteModel(
            name='PropertyImage',
        ),
    ]
