# Generated by Django 5.2.5 on 2026-01-15 08:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitrequest',
            name='visit_date',
        ),
        migrations.AddField(
            model_name='visitrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visitrequest',
            name='message',
            field=models.TextField(blank=True),
        ),
    ]
